### ISSUE TITLE
Relationship inclusion in views can result in duplicate resources

### ISSUE THREAD

**Issue by backspace** [beam-community/jsonapi#348]
Thanks for all the work on this, it’s made things pretty smooth apart from my problem here. I have an application where I want JSON responses to include a lot of related resources but I’m getting semi-duplication.

A run has many participations, I also need to preload the participation’s run so it can be correlated on the client, and the participation’s user. This results in a response that has duplicate participations in the `included` block with different relationships, and even the root run is in there.

Here’s an example response with irrelevant parts removed:

<table>
<tbody>
<tr>
<td>
<pre>
{
  "data": [
    {
      "attributes": {…},
      "id": "59e1382a-2cf1-4fc5-abd5-e5a22cc213e2",
      "links": {…},
      "type": "runs",
      "relationships": {
        "specification": {…},
        "participations": {
          "data": [
            {
              "id": "6098e3cb-f58e-4e48-9ceb-0ef6b55e38a0",
              "type": "participations"
            }
          ],
          "links": {…}
        },
        "submissions": {…}
      }
    }
  ],
  "links": {…},
</pre>
</td>
<td>The root run</td>
</tr>
<td>
<pre>
  "included": [
    …,
    {
      "attributes": {
        "ready_at": null
      },
      "id": "6098e3cb-f58e-4e48-9ceb-0ef6b55e38a0",
      "links": {…},
      "type": "participations",
      "relationships": {}
    },
</pre>
</td>
<td>An included participation with no relationships</td>
</tr>
<tr>
<td>
<pre>
    {
      "attributes": {…},
      "id": "59e1382a-2cf1-4fc5-abd5-e5a22cc213e2",
      "links": {…},
      "type": "runs",
      "relationships": {
        "specification": {
          "data": {
            "id": "a5b1b47e-a180-4ca0-95e4-75888b630901",
            "type": "specifications"
          },
          "links": {…}
        },
        "participations": {
          "data": [
            {
              "id": "6098e3cb-f58e-4e48-9ceb-0ef6b55e38a0",
              "type": "participations"
            }
          ],
          "links": {…}
        },
        "submissions": {…}
      }
    },
</pre>
</td>
<td>The root run again, included because <code>ParticipationView</code> includes <code>run</code>.</td>
</tr>
<tr>
<td>
<pre>
    {
      "attributes": {…},
      "id": "6098e3cb-f58e-4e48-9ceb-0ef6b55e38a0",
      "links": {…},
      "type": "participations",
      "relationships": {
        "run": {
          "data": {
            "id": "59e1382a-2cf1-4fc5-abd5-e5a22cc213e2",
            "type": "runs"
          },
          "links": {…}
        }
      }
    },
</pre>
</td>
<td>An included participation lacking its <code>user</code> relationship.</td>
</tr>
<tr>
<td>
<pre>
    …,
    {
      "attributes": {…},
      "id": "6098e3cb-f58e-4e48-9ceb-0ef6b55e38a0",
      "links": {…},
      "type": "participations",
      "relationships": {
        "run": {
          "data": {
            "id": "59e1382a-2cf1-4fc5-abd5-e5a22cc213e2",
            "type": "runs"
          },
          "links": {…}
        },
        "user": {
          "data": {
            "id": "ce8112be-a9db-4ef1-ae1a-4d75a1916975",
            "type": "users"
          },
          "links": {…}
        }
      }
    }
  ]
}
</pre>
</td>
<td>The same relationship, now including its <code>user</code>.</td>
</tr>
</tbody>
</table>

This double inclusion means I need [defensive client code](https://github.com/backspace/adventures/blob/acc8b805653ce9eff9cb7dc4e52e806e6c5b3d1f/waydowntown_app/lib/models/run.dart#L61) to select the included resource that has the expected relationships.

I have baroque preloads to span the object graph, further complicated by the `users` table being in another Postgres schema:

```elixir
    Run
    |> filter_runs_query(filters)
    |> Repo.all()
    |> Repo.preload(run_preloads())
    |> Repo.preload(participations: [run: run_preloads()])
    |> Repo.preload([participations: [:user]], prefix: "public")
```

And my views are mutually referencing:

```elixir
defmodule RegistrationsWeb.ParticipationView do
  use JSONAPI.View, type: "participations"
  …
  def relationships do
    [run: {RegistrationsWeb.RunView, :include}, user: {RegistrationsWeb.JSONAPI.UserView, :include}]
  end
end

defmodule RegistrationsWeb.RunView do
  use JSONAPI.View, type: "runs"
  …
  def relationships do
    [
      participations: {RegistrationsWeb.ParticipationView, :include},
      specification: {RegistrationsWeb.SpecificationView, :include},
      submissions: {RegistrationsWeb.SubmissionView, :include}
    ]
  end
end

```

It may be that this library can’t properly deduplicate included resources because it has no way of knowing which is correct to choose. But is there any best practice for getting this chaos under control? 😳

**Comment by mattpolzin** [comment]
I’ll start by saying that the library does attempt to deduplicate includes so it is possible there’s room for improvement here. 

The current deduplication uses `Enum.uniq/1` so it isn’t going to see two resources that will be serialized differently as the same even if they have the same type/id which is theoretically the only thing that should be considered in identifying a JSON:API resource. 

The fact that you get the primary resource also serialized in the includes because some other include refers to it sounds like desired behavior to me.

I think that leaves the question of includes that are indeed the same (same type/id) but are showing up twice in your responses. As I said above, this does feel like an area with room for improvement, but it leaves us with the question you posed above: how should we choose between two copies of the same resource with different fields/relationships on them? At some level the fact that the “same” resource has different attributes feels a bit counter to JSON:API, but I don’t think we need to debate that here per se. The easiest thing for you to do would be to find a way to control the shape of a given resource based on the request being made and therefore serialized a given resource the same way each time for a single request; this would alleviate the question of how to choose one and it would also fix the issue of duplication since `Enum.uniq/1` would catch the duplicates.

**Comment by backspace** [comment]
👍🏻 thanks for the clarification that deduplication does happen, then it seems you’re right that I need consistent serialisation of the object graph regardless of the starting point. I’ve made some efforts in that direction but have so far failed. I’ll keep trying though, thanks!

**Comment by mattpolzin** [comment]
I do wonder if it’s worth a duplication function that can optionally be configured. I have not thought on whether such a thing is worth it for the library but there’s a chance it would be because regardless of whether I personally would like to see a resource serialized the same way in all places I think including a resource twice in the includes with the same type/id is not good. It’s probably worse that the library makes it easy to end up in that situation than it would be to provide a way to handle deduplication explicitly.

**Comment by backspace** [comment]
ya an escape valve when an abstraction is failing is often helpful! I’d definitely make use of that feature in the event I can’t figure out a clean way to normalise my tangled object graph 🤓
